<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;
use phpDocumentor\Reflection\Types\This;

class Category extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function (Category $cat) {
            $cat->slug = Str::slug($cat->title);
        });

        self::deleting(function (Category $cat){
            $cat->subjects()->each(function ($subject){
                $subject->delete();
            });
        });
    }

    // Article model
    public function getRouteKeyName()
    {
        return 'slug';
    }

    protected $fillable = [
        'title',
        'slug',
    ];


    public function subjects()
    {
        return $this->hasMany(Subject::class, 'category_id', 'id');
    }

}
