<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Module extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->slug = Str::slug($model->name);
        });

        self::deleting(function (Module $module) {


        });;
    }

    protected $fillable = [
        'name',
        'slug',
        'description',
        'subject_id',
    ];


    protected $appends = [
        'is_completed',
        'mark'
    ];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function subject()
    {
        return $this->belongsTo(Subject::class, 'subject_id', 'id');
    }

    public function objectives(){
        return $this->hasMany(Objective::class,'module_id','id');
    }


    public function VideoObjectives()
    {
        return $this->objectives()->whereHas('media');
    }

    public function ReadingObjectives()
    {
        return $this->objectives()->doesntHave('media');
    }

    public function getMarkAttribute(){
        $examsCount = $this->exams()->count();
        $mark = 0;
        foreach ($this->exams as $exam){
            $submit = $exam->authSubmit()->first();
            if ($submit){
                $mark+= $submit->final_mark;
            }
        }

        return $mark / $examsCount;

    }
    public function getIsCompletedAttribute()
    {
        $examsCount = $this->exams()->count();
        $submitsCount = 0;
        if ($examsCount > 0){
            foreach ($this->exams as $exam){

                $submit = $exam->authSubmit()->first();
                if ($submit){
                    $submitsCount++;
                }
            }
        }
       // $examComplete = $this->exams ? $this->exam->authSubmit()->first() : null;

//        $objectives = $this->objectives;
//        $objectiveSeen = 0;
//        foreach ($objectives as $objective) {
//            if ($objective->isSeen->first()) {
//                $objectiveSeen++;
//            }
//
//        }

        if ($examsCount == $submitsCount){
            return true;
        }
//        if (($this->exam && $examComplete) /*&& $objectiveSeen == $objectives->count()*//* || (!$this->exam ) *//*&& $objectiveSeen == $objectives->count()*/) {
//            return true;
//        }


        return false;
    }


    public function assignments(){
        return $this->hasMany(Assignment::class,'module_id','id');
    }


    public function exams(){
        return $this->hasMany(Exam::class,'module_id','id');
    }

}
