<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;


class Subject extends Model implements HasMedia
{
    use HasFactory, HasMediaTrait;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->slug = Str::slug($model->name);
        });

        self::deleting(function (Subject $subject) {
            if ($subject->hasMedia('cover')) {
                $subject->getFirstMedia('cover')->delete();
            }

            $subject->modules()->each(function ($module){
                $module->delete();
            });

        });
    }

    protected $fillable = [
        'name',
        'slug',
        'description',
        'category_id',
        'creator_id',
    ];


    public function getRouteKeyName()
    {
        return 'slug';
    }


    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }

    public function modules(){
        return $this->hasMany(Module::class,'subject_id','id');
    }
}
